# Generated by Django 4.2 on 2023-05-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar'), ('ABA', 'aban token'), ('BTC', 'bitcoin')], default=None, editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(10), djmoney.models.validators.MaxMoneyValidator(1500)])),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
